[package]
name = "dectest"
authors = ["Materialize, Inc."]
description = "Decimal test driver."
version = "0.0.0"
edition = "2018"
publish = false

[dependencies]
dec = { path = "../dec" }
hex = "0.4.2"
